//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGestion.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaDeGestion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _061 {
            get {
                object obj = ResourceManager.GetObject("061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addres_book {
            get {
                object obj = ResourceManager.GetObject("addres_book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap advancedsettings {
            get {
                object obj = ResourceManager.GetObject("advancedsettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agregar_icono_5633_16 {
            get {
                object obj = ResourceManager.GetObject("agregar-icono-5633-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap anadido_excluir_de_compra_en_linea_de_comercio_electronico_de_la_tienda_icono_9156_128 {
            get {
                object obj = ResourceManager.GetObject("anadido-excluir-de-compra-en-linea-de-comercio-electronico-de-la-tienda-icono-915" +
                        "6-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap anadido_excluir_de_compra_en_linea_de_comercio_electronico_de_la_tienda_icono_9156_1281 {
            get {
                object obj = ResourceManager.GetObject("anadido-excluir-de-compra-en-linea-de-comercio-electronico-de-la-tienda-icono-915" +
                        "6-1281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap beos_consulta_icono_6152_128 {
            get {
                object obj = ResourceManager.GetObject("beos-consulta-icono-6152-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap beos_consulta_icono_6152_1281 {
            get {
                object obj = ResourceManager.GetObject("beos-consulta-icono-6152-1281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blockdevice {
            get {
                object obj = ResourceManager.GetObject("blockdevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blockdevice1 {
            get {
                object obj = ResourceManager.GetObject("blockdevice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buscar_buscar_ampliar_icono_9048_16 {
            get {
                object obj = ResourceManager.GetObject("buscar-buscar-ampliar-icono-9048-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camion_lorrygreen_icono_9499_128 {
            get {
                object obj = ResourceManager.GetObject("camion-lorrygreen-icono-9499-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camion_venido {
            get {
                object obj = ResourceManager.GetObject("camion_venido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancelar_icono_4624_48 {
            get {
                object obj = ResourceManager.GetObject("cancelar-icono-4624-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancelar_icono_4624_481 {
            get {
                object obj = ResourceManager.GetObject("cancelar-icono-4624-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancelar_icono_4624_482 {
            get {
                object obj = ResourceManager.GetObject("cancelar-icono-4624-482", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap carritonoimpreso {
            get {
                object obj = ResourceManager.GetObject("carritonoimpreso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap carritonoimpreso1 {
            get {
                object obj = ResourceManager.GetObject("carritonoimpreso1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap carritonoimpreso2 {
            get {
                object obj = ResourceManager.GetObject("carritonoimpreso2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cerca_de_la_cruz_eliminar_la_salida_de_error_icono_5953_128 {
            get {
                object obj = ResourceManager.GetObject("cerca-de-la-cruz-eliminar-la-salida-de-error-icono-5953-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clase_icono_9621_128 {
            get {
                object obj = ResourceManager.GetObject("clase-icono-9621-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Community_Help {
            get {
                object obj = ResourceManager.GetObject("Community Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copiar_los_archivos_de_documentos_de_icono_4275_16 {
            get {
                object obj = ResourceManager.GetObject("copiar-los-archivos-de-documentos-de-icono-4275-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copiar_los_archivos_de_documentos_de_icono_4275_161 {
            get {
                object obj = ResourceManager.GetObject("copiar-los-archivos-de-documentos-de-icono-4275-161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corrector_ortografico_icono_5850_128 {
            get {
                object obj = ResourceManager.GetObject("corrector-ortografico-icono-5850-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cuenta_icono_6432_128 {
            get {
                object obj = ResourceManager.GetObject("cuenta-icono-6432-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cuenta_icono_6432_1281 {
            get {
                object obj = ResourceManager.GetObject("cuenta-icono-6432-1281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dibujo_a_lapiz_modificar_escribir_icono_8118_16 {
            get {
                object obj = ResourceManager.GetObject("dibujo-a-lapiz-modificar-escribir-icono-8118-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dollar_sign {
            get {
                object obj = ResourceManager.GetObject("dollar_sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap e_mail_sobre_icono_5597_128 {
            get {
                object obj = ResourceManager.GetObject("e-mail-sobre-icono-5597-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap e_mail_sobre_icono_5597_1281 {
            get {
                object obj = ResourceManager.GetObject("e-mail-sobre-icono-5597-1281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eliminar_icono_4912_16 {
            get {
                object obj = ResourceManager.GetObject("eliminar-icono-4912-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eliminar_icono_4912_32 {
            get {
                object obj = ResourceManager.GetObject("eliminar-icono-4912-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap encontrar_busqueda_zoom_icono_6513_128 {
            get {
                object obj = ResourceManager.GetObject("encontrar-busqueda-zoom-icono-6513-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap explorador_de_archivos_icono_6698_16 {
            get {
                object obj = ResourceManager.GetObject("explorador-de-archivos-icono-6698-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap explorador_de_archivos_icono_6698_161 {
            get {
                object obj = ResourceManager.GetObject("explorador-de-archivos-icono-6698-161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_Search {
            get {
                object obj = ResourceManager.GetObject("Folder Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guardar_archivo_icono_6713_16 {
            get {
                object obj = ResourceManager.GetObject("guardar-archivo-icono-6713-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guardar_archivo_icono_6713_161 {
            get {
                object obj = ResourceManager.GetObject("guardar-archivo-icono-6713-161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hardware_Laser_Printer_icon {
            get {
                object obj = ResourceManager.GetObject("Hardware-Laser-Printer-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hoja_de_calculo_excel_invoice_icono_5449_128 {
            get {
                object obj = ResourceManager.GetObject("hoja-de-calculo-excel-invoice-icono-5449-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hojacalculorojo {
            get {
                object obj = ResourceManager.GetObject("hojacalculorojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imprimir_icono_4607_16 {
            get {
                object obj = ResourceManager.GetObject("imprimir-icono-4607-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imprimir_icono_5119_16 {
            get {
                object obj = ResourceManager.GetObject("imprimir-icono-5119-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kdmconfig {
            get {
                object obj = ResourceManager.GetObject("kdmconfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kuser {
            get {
                object obj = ResourceManager.GetObject("kuser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap microsoft_office_word_2003_icono_8261_16 {
            get {
                object obj = ResourceManager.GetObject("microsoft-office-word-2003-icono-8261-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moneda_verde_dinero_en_efectivo_en_dolares_icono_5593_16 {
            get {
                object obj = ResourceManager.GetObject("moneda-verde-dinero-en-efectivo-en-dolares-icono-5593-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap negocios_monedas_de_plata_metalica_de_pago_dolar_icono_8061_64 {
            get {
                object obj = ResourceManager.GetObject("negocios-monedas-de-plata-metalica-de-pago-dolar-icono-8061-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pagina_copiar_icono_4625_16 {
            get {
                object obj = ResourceManager.GetObject("pagina-copiar-icono-4625-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paquete_de_caja_icono_5213_128 {
            get {
                object obj = ResourceManager.GetObject("paquete-de-caja-icono-5213-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paquete_de_caja_icono_5213_16 {
            get {
                object obj = ResourceManager.GetObject("paquete-de-caja-icono-5213-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap recyclebin_vacio_icono_9473_16 {
            get {
                object obj = ResourceManager.GetObject("recyclebin-vacio-icono-9473-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap si_puede_aceptar_icono_7881_16 {
            get {
                object obj = ResourceManager.GetObject("si-puede-aceptar-icono-7881-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tienda_de_compras_del_ecommerce_icono_5258_128 {
            get {
                object obj = ResourceManager.GetObject("tienda-de-compras-del-ecommerce-icono-5258-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tienda_de_compras_del_ecommerce_icono_5258_1281 {
            get {
                object obj = ResourceManager.GetObject("tienda-de-compras-del-ecommerce-icono-5258-1281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap usuarios_de_la_persona_icono_7851_128 {
            get {
                object obj = ResourceManager.GetObject("usuarios-de-la-persona-icono-7851-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ver_icono_5784_16 {
            get {
                object obj = ResourceManager.GetObject("ver-icono-5784-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
